# Generated by Django 6.1.1 on 2026-09-03 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('role', models.CharField(blank=True, help_text="e.g. 'Design & development, solo'", max_length=120)),
                ('year', models.CharField(blank=True, help_text="e.g. '2024' or '2023–24'", max_length=9)),
                ('summary', models.CharField(help_text='One line, shown in the index.', max_length=240)),
                ('body', models.TextField(help_text='Longer write-up. Plain paragraphs, one per line.')),
                ('cover_alt', models.CharField(blank=True, help_text='Description used in place of an image.', max_length=200)),
                ('link_url', models.URLField(blank=True)),
                ('link_label', models.CharField(blank=True, default='View live', max_length=60)),
                ('repo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('in_progress', 'In progress'), ('archived', 'Archived')], default='live', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='core.tag')),
            ],
            options={
                'ordering': ['order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('dek', models.CharField(help_text='Standfirst / subheading shown under the title.', max_length=240)),
                ('body', models.TextField(help_text='Plain paragraphs, one per line. First paragraph gets a drop cap.')),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reading_minutes', models.PositiveIntegerField(default=4)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='core.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
