# Generated by Django 6.1.1 on 2026-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Onah Samuel Iyojeni', max_length=120)),
                ('tagline', models.CharField(default='Software engineer · graphic designer · entrepreneur', max_length=160)),
                ('hero_heading', models.CharField(blank=True, help_text='Leave blank to use your full name.', max_length=120)),
                ('hero_text', models.TextField(default='I build software, design the visual identity around it, and start the ventures that need both.', help_text='Shown under your name on the home page.')),
                ('bio', models.TextField(blank=True, help_text='Your About page bio. Plain paragraphs, one per line.')),
                ('portrait', models.ImageField(blank=True, help_text='Shown on the About page.', null=True, upload_to='profile/')),
                ('hero_image', models.ImageField(blank=True, help_text='Optional. Shown behind the home page hero if set.', null=True, upload_to='profile/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('availability', models.CharField(blank=True, default='Open to internships, freelance work, and collaborations', max_length=160)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Shown on the index and at the top of the post.', null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Shown on the index and at the top of the project page.', null=True, upload_to='projects/'),
        ),
    ]
